INSERT INTO prodotto VALUES (NULL, "Anatra", "Carne",  8.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Arrosto",  9.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Bollito c.o.",  7.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Bollito misto",  8.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Bollito polpa",  9.30, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Brasato",  9.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Carbonada",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Carne trita",  8.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Carne trita magra",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Carne trita sugo",  5.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Coda",  6.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Coscia",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Fegato",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Fettine",  14.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Franburger",  11.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Hamburger",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Lingua",  7.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Lingua cotta salmistrata",  16.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Nodino",  16.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Ossibuchi",  9.30, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Polpa per bollito muscolo",  9.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Polpa per vitello tonnato",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Presalé",  11.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Reale",  8.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Ritagli per ragù",  4.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Rognone",  5.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Rolate",  9.30, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Scaloppine",  14.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Scamone",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Sottofiletto a fette",  16.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Sottofiletto intero",  15.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Spalla cotta Nadia",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Spezzatino",  8.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Spiedoburger",  11.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Svizzera",  15.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Tondino",  15.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Trippa",  6.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Bovino", "Filetto vitellone",  28.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Coniglio", "Carne",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Faraona", "Carne",  8.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Arrosto",  6.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Capocollo",  6.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Costine",  5.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Cotechino",  7.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Filetto",  11.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Lonza",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Pasta salsiccia",  7.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Porchetta",  16.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Salsiccia",  8.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Maiale", "Stinchi",  5.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Fagottini",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Giardiniera",  12.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Gressonare",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Involtini",  16.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Polpette",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Spiedini",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Misto", "Tramezzini",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Bocconcini",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Cappone",  11.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Cosce",  5.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Fegatini",  5.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Fettine",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Pollo", "Fusi",  6.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Bon Bocon Bertolin",  16.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Bresaola",  30.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Coppa",  18.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Lardo Arnad Bertolin",  13.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Lardo della casa",  11.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Mocetta",  30.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Mocetta affettata",  33.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Mortadella",  12.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Pancetta coppata",  18.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Prosciutto cotto",  19.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Prosciutto cotto spalla",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Prosciutto crudo",  26.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Rosa d'Aosta",  28.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Salame contadino",  18.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Salame cotto Nadia",  10.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Salamini Bertolin",  16.50, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Salumi", "Speck",  18.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Arrosto cotto",  16.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Cosce",  4.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Fesa",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Fettine",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Rolate",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Tacchino", "Spezzatino",  9.00, 10, 0);
INSERT INTO prodotto VALUES (NULL, "Uova", "Dozzina",  3.80, 10, 0);
